openapi: 3.0.3
info:
  title: Yo' Mama - The Roast API - Swagger UI
  version: 1.0.0
  description: 'RESTful implementation of a light hearted Roast Insult API '
  contact:
    name: Terry A. Brooks, Jr.
    url: https://brooksjr.com
    email: terry@brooksjr.com
paths:
  /api/insult:
    get:
      operationId: api_insult_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insult'
              examples:
                ExampleInsult:
                  value:
                    pk: 1
                    content: You're so slow, it takes you an hour to cook minute rice.
                    category: stupid
                    NSFW: false
                    added_on: '2024-09-25'
                    added_by: john_doe
                  summary: Example of an Insult
                  description: This example represents an insult, categorized and
                    created by a user.
          description: ''
  /api/insults/{id}:
    get:
      operationId: api_insults_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insult'
              examples:
                ExampleInsult:
                  value:
                    pk: 1
                    content: You're so slow, it takes you an hour to cook minute rice.
                    category: stupid
                    NSFW: false
                    added_on: '2024-09-25'
                    added_by: john_doe
                  summary: Example of an Insult
                  description: This example represents an insult, categorized and
                    created by a user.
          description: ''
  /api/insults/categories:
    get:
      operationId: api_insults_categories_retrieve
      description: 'API GET Endpoint returning all the Insults Submitted by the Authenticated
        User. Will Return '
      tags:
      - Insults
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/insults/category/{category}:
    get:
      operationId: api_insults_category_list
      parameters:
      - in: path
        name: category
        schema:
          type: string
        required: true
      - in: query
        name: category
        schema:
          type: string
          enum:
          - B
          - DO
          - DS
          - F
          - H
          - L
          - N
          - O
          - P
          - S
          - SKN
          - SNWF
          - SRT
          - T
          - TEST
          - U
        description: |-
          * `P` - poor
          * `F` - fat
          * `U` - ugly
          * `S` - stupid
          * `SNWF` - snowflake
          * `O` - old
          * `DO` - old_daddy
          * `DS` - stupid_daddy
          * `N` - nasty
          * `T` - tall
          * `TEST` - testing
          * `SKN` - skinny
          * `B` - bald
          * `H` - hairy
          * `L` - lazy
          * `SRT` - short
      - in: query
        name: nsfw
        schema:
          type: boolean
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedInsultList'
              examples:
                GettingAllJokesInACategory:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - count: 401
                      next: http://127.0.0.1:8000/api/insults/P?page=2
                      previous: 'null'
                      results:
                      - id: 979885544274460700
                        content: Yo mama so bald, you can see whatâ€™s on her mind.
                      - id: 979885544274657300
                        content: Yo momma is so bald... you can see what's on her
                          mind.
                      - id: 979885544274690000
                        content: Yo momma is so bald... even a wig wouldn't help!
                      - id: 979885544274722800
                        content: Yo momma is so bald... she had to braids her beard.
                  summary: Paginated Listing of all active jokes in  a category
                  description: This endpoint allows API Consumers to get a paginated
                    list of all jokes in a given category i.e. "fat", "poor", "etc.
          description: ''
  /api/schema:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/user/insults/:
    post:
      operationId: api_user_insults_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyInsult'
            examples:
              SimplifiedInsultExample:
                value:
                  category: stupid
                  content: You bring everyone so much joy, when you leave the room.
                  status: approved
                summary: Simplified Insult Serializer Example
                description: This example represents a simplified version of an insult
                  for specific API views.
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyInsult'
              examples:
                SimplifiedInsultExample:
                  value:
                    category: stupid
                    content: You bring everyone so much joy, when you leave the room.
                    status: approved
                  summary: Simplified Insult Serializer Example
                  description: This example represents a simplified version of an
                    insult for specific API views.
          description: ''
    put:
      operationId: api_user_insults_update
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyInsult'
            examples:
              SimplifiedInsultExample:
                value:
                  category: stupid
                  content: You bring everyone so much joy, when you leave the room.
                  status: approved
                summary: Simplified Insult Serializer Example
                description: This example represents a simplified version of an insult
                  for specific API views.
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyInsult'
              examples:
                SimplifiedInsultExample:
                  value:
                    category: stupid
                    content: You bring everyone so much joy, when you leave the room.
                    status: approved
                  summary: Simplified Insult Serializer Example
                  description: This example represents a simplified version of an
                    insult for specific API views.
          description: ''
    delete:
      operationId: api_user_insults_destroy
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /auth/users/:
    get:
      operationId: auth_users_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
    post:
      operationId: auth_users_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
  /auth/users/{id}/:
    get:
      operationId: auth_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: auth_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: auth_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: auth_users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /auth/users/activation/:
    post:
      operationId: auth_users_activation_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activation'
          description: ''
  /auth/users/me/:
    get:
      operationId: auth_users_me_retrieve
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: auth_users_me_update
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: auth_users_me_partial_update
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: auth_users_me_destroy
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /auth/users/resend_activation/:
    post:
      operationId: auth_users_resend_activation_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailReset'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEmailReset'
          description: ''
  /auth/users/reset_password/:
    post:
      operationId: auth_users_reset_password_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailReset'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEmailReset'
          description: ''
  /auth/users/reset_password_confirm/:
    post:
      operationId: auth_users_reset_password_confirm_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResetConfirm'
          description: ''
  /auth/users/reset_username/:
    post:
      operationId: auth_users_reset_username_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailReset'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEmailReset'
          description: ''
  /auth/users/reset_username_confirm/:
    post:
      operationId: auth_users_reset_username_confirm_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsernameResetConfirm'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsernameResetConfirm'
          description: ''
  /auth/users/set_password/:
    post:
      operationId: auth_users_set_password_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetPassword'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetPassword'
          description: ''
  /auth/users/set_username/:
    post:
      operationId: auth_users_set_username_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetUsername'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetUsername'
          description: ''
  /report-joke:
    post:
      operationId: report_joke_create
      tags:
      - report-joke
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JokeReport'
            examples:
              JokeReportExample:
                value:
                  id: 1
                  insult: 5
                  reviewer: admin
                  review_comment: This insult is a bit too harsh.
                  reviewed_on: '2024-09-27'
                summary: Joke Report Serializer Example
                description: An example report for an insult that was reviewed.
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokeReport'
              examples:
                JokeReportExample:
                  value:
                    id: 1
                    insult: 5
                    reviewer: admin
                    review_comment: This insult is a bit too harsh.
                    reviewed_on: '2024-09-27'
                  summary: Joke Report Serializer Example
                  description: An example report for an insult that was reviewed.
          description: ''
components:
  schemas:
    Activation:
      type: object
      properties:
        uid:
          type: string
        token:
          type: string
      required:
      - token
      - uid
    BlankEnum:
      enum:
      - ''
    CategoryEnum:
      enum:
      - P
      - F
      - U
      - S
      - SNWF
      - O
      - DO
      - DS
      - N
      - T
      - TEST
      - SKN
      - B
      - H
      - L
      - SRT
      type: string
      description: |-
        * `P` - poor
        * `F` - fat
        * `U` - ugly
        * `S` - stupid
        * `SNWF` - snowflake
        * `O` - old
        * `DO` - old_daddy
        * `DS` - stupid_daddy
        * `N` - nasty
        * `T` - tall
        * `TEST` - testing
        * `SKN` - skinny
        * `B` - bald
        * `H` - hairy
        * `L` - lazy
        * `SRT` - short
    Insult:
      type: object
      description: Serializer for Insult model to convert model instances to Python
        data types.
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        content:
          type: string
        category:
          $ref: '#/components/schemas/CategoryEnum'
        NSFW:
          type: boolean
        added_on:
          type: string
          format: date
        added_by:
          type: string
          readOnly: true
      required:
      - NSFW
      - added_by
      - added_on
      - category
      - content
      - pk
    JokeReport:
      type: object
      description: Serializer for InsultReview model.
      properties:
        id:
          type: integer
          readOnly: true
        anonymous:
          type: boolean
        reporter_first_name:
          type: string
          nullable: true
          maxLength: 80
        reporter_last_name:
          type: string
          nullable: true
          maxLength: 80
        post_review_contact_desired:
          type: boolean
        reporter_email:
          type: string
          format: email
          nullable: true
          maxLength: 254
        date_submitted:
          type: string
          format: date
          readOnly: true
        date_reviewed:
          type: string
          format: date
          nullable: true
        rationale_for_review:
          type: string
        review_type:
          $ref: '#/components/schemas/ReviewTypeEnum'
        status:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/StatusEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        insult_id:
          type: integer
      required:
      - date_submitted
      - id
      - insult_id
      - rationale_for_review
      - review_type
    MyInsult:
      type: object
      description: Serializer for simplified Insult representation.
      properties:
        category:
          type: string
        content:
          type: string
          maxLength: 65535
        status:
          type: string
          readOnly: true
      required:
      - category
      - content
      - status
    NullEnum:
      enum:
      - null
    PaginatedInsultList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Insult'
    PaginatedUserList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PasswordResetConfirm:
      type: object
      properties:
        uid:
          type: string
        token:
          type: string
        new_password:
          type: string
      required:
      - new_password
      - token
      - uid
    PatchedUser:
      type: object
      properties:
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
    ReviewTypeEnum:
      enum:
      - RE
      - RC
      - RX
      type: string
      description: |-
        * `RE` - Joke Reclassification
        * `RC` - Joke Recategorization
        * `RX` - Joke Removal
    SendEmailReset:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    SetPassword:
      type: object
      properties:
        new_password:
          type: string
        current_password:
          type: string
      required:
      - current_password
      - new_password
    SetUsername:
      type: object
      properties:
        current_password:
          type: string
        new_username:
          type: string
          title: Username
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
      required:
      - current_password
      - new_username
    StatusEnum:
      enum:
      - P
      - NCE
      - SCE
      - NJC
      - SJC
      - X
      type: string
      description: |-
        * `P` - Pending
        * `NCE` - Completed - New Explicitly Setting
        * `SCE` - Completed - No New Explicitly Setting
        * `NJC` - Completed - Assigned to New Category
        * `SJC` - Completed - No New Category Assigned
        * `X` - Completed - Joke Removed
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
      required:
      - id
      - username
    UserCreate:
      type: object
      properties:
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        id:
          type: integer
          readOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - id
      - password
      - username
    UsernameResetConfirm:
      type: object
      properties:
        new_username:
          type: string
          title: Username
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
      required:
      - new_username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
externalDocs:
  url: https://github.com/Terry-BrooksJr/the-dozens-django
  description: GitHub Repository and full API documentation Hub
